pipeline {

    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/abhiram-bency/Predictive-fleet-maintenance-model-.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -f devops/Dockerfile -t fleet-maintenance-app .'
            }
        }

        stage('Stop Existing Container') {
            steps {
                bat 'docker stop fleet-container || exit 0'
                bat 'docker rm fleet-container || exit 0'
            }
        }

        stage('Deploy New Container') {
            steps {
                bat 'docker run -d -p 8501:8501 --name fleet-container fleet-maintenance-app'
            }
        }

    }
}